name: Upload to Alidrive

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL(HTTP/HTTPS OR Metalink)'
        required: true
      path:
        description: 'Video File Path(Wildcard support)'
        required: true      

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Aria2/FFmpeg/Uploader
        run: |
          python ./aria2/add_tracker.py
          wget -q https://github.com/eugeneware/ffmpeg-static/releases/latest/download/linux-x64 -O /usr/local/bin/ffmpeg
          chmod +x /usr/local/bin/ffmpeg
          wget -q https://github.com/aoaostar/alidrive-uploader/releases/download/v2.0.2/alidrive_uploader_v2.0.2_linux_amd64.tar.gz
          tar xf alidrive_uploader_v2.0.2_linux_amd64.tar.gz
          mv alidrive_uploader_linux_amd64/alidrive /usr/local/bin/alidrive
          chmod +x /usr/local/bin/alidrive

      - name: Download Video
        run: |
          aria2c --conf-path=./aria2/aria2.conf "${{ github.event.inputs.url }}"

      - name: Upload to Alidrive
        env:
          drive_id: ${{ secrets.DRIVE_ID }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
        run: |
          sed -i "s/did/$drive_id/;s/rtoken/$refresh_token/" alidrive.yaml
          videos=(${{ github.event.inputs.path }})
          for video in $videos;do
            echo "$video"
            ffmpeg -hide_banner -y -i "$video" -metadata random="$RANDOM" -c copy "$video"
            ./alidrive -c alidrive.yaml "$video" Video
          done
