name: Upload to Alidrive(Random)

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL(HTTP/HTTPS OR Metalink)'
        required: true
      path:
        description: 'Video File Path(Wildcard support)'
        required: true      

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Tranmission/Uploader
        run: |
          sudo apt install transmission-cli -y
          echo "net.core.rmem_max = 4194304" | sudo tee -a /etc/sysctl.conf
          echo "net.core.wmem_max = 1048576" | sudo tee -a /etc/sysctl.conf
          sudo sysctl -p
          curl -sL https://raw.githubusercontent.com/aoaostar/alidrive-uploader/v2/install.sh | bash
          mv alidrive_uploader_linux_amd64/alidrive /usr/local/bin/alidrive && chmod +x /usr/local/bin/alidrive

      - name: Download Video
        run: |
          transmission-cli -g ./transmission -w . "${{ github.event.inputs.url }}"

      - name: Upload to Alidrive
        env:
          drive_id: ${{ secrets.DRIVE_ID }}
          refresh_token: ${{ secrets.REFRESH_TOKEN }}
        run: |
          sed -i "s/did/$drive_id/;s/rtoken/$refresh_token/" alidrive.yaml
          videos=("${{ github.event.inputs.path }}")
          for video in $videos;do
            echo -n $RANDOM >> "$video"
            alidrive -c alidrive.yaml "$video" Video
          done
