name: Zip to Artifact

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Video URL(HTTP/HTTPS OR Metalink)'
        required: true
      path:
        description: 'Video File Path(Wildcard support)'
        required: true
      name:
        description: 'Artifact Name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Aria2
        run: |
            df -h ./
            python aria2.py
            wget -q https://github.com/P3TERX/aria2.conf/raw/master/dht.dat
            wget -q https://github.com/P3TERX/aria2.conf/raw/master/dht6.dat

      - name: Download Video
        run: |
            aria2c --conf-path=./aria2.conf "${{ github.event.inputs.url }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.name }}
          path: ${{ github.event.inputs.path }}
