name: AV1 Test

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Video URL(HTTP/HTTPS OR Metalink)'
        required: true
      video:
        description: 'Video File Path(Wildcard support)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Aria2/FFmpeg
        run: |
          python ./aria2/add_tracker.py
          wget -q https://github.com/eugeneware/ffmpeg-static/releases/latest/download/linux-x64 -O /usr/local/bin/ffmpeg
          chmod +x /usr/local/bin/ffmpeg

      - name: Download video
        run: | 
            aria2c --conf-path=./aria2/aria2.conf "${{ github.event.inputs.url }}"

      - name: Process video
        run: |
          ffmpeg -h encoder=libx265
          ffmpeg -hide_banner -i ${{ github.event.inputs.video }} -c:v libx265 op.mp4
          ls -ll
          
