name: Delete All Log

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Install dependence
        run: |
          pip install ghapi
      
      - name: Setup task
        run: |
            python3 delog.py