name: Update DHT

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL(HTTP/HTTPS OR Metalink)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Download Video
        run: |
            python ./aria2/add_tracker.py
            sed -i 's/seed-time=0//g' ./aria2/aria2.conf
            aria2c --conf-path=./aria2/aria2.conf "${{ github.event.inputs.url }}"

      - name: Update DHT
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git add ./aria2/dht.dat ./aria2/dht6.dat
          git commit -m 'update'
          git push -f origin main