name: Transmission-cli

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL(HTTP/HTTPS OR Metalink)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup
        run: |
            sudo apt install transmission-cli -y
      
      - name: DL
        run: |
            transmission-cli -er -g ./transimission -w ./ "${{ github.event.inputs.url }}"

      - name: Update repo
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git add ./transmission
          git commit -m 'update'
          git push -f origin main