name: Raw Video to Release

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Video URL(HTTP/HTTPS OR Metalink)'
        required: true
      path:
        description: 'Video File Path(Wildcard support)'
        required: true
      tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Download video
        run: |
            python aria2.py
            wget -q https://github.com/P3TERX/aria2.conf/raw/master/dht.dat
            wget -q https://github.com/P3TERX/aria2.conf/raw/master/dht6.dat
            aria2c --conf-path=./aria2.conf ${{ github.event.inputs.url }}

      - name: Release Video
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.event.inputs.tag }}
          prerelease: false
          files: |
            ${{ github.event.inputs.path }}
