name: Raw to Release

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Video URL(HTTP/HTTPS OR Metalink)'
        required: true
      path:
        description: 'Video File Path(Wildcard support)'
        required: true
      tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          #remove-dotnet: 'true'
          #remove-android: 'true'
          #remove-haskell: 'true'

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Aria2
        run: |
            python aria2.py
            wget -q https://github.com/P3TERX/aria2.conf/raw/master/dht.dat
            wget -q https://github.com/P3TERX/aria2.conf/raw/master/dht6.dat

      - name: Download video
        run: |
            aria2c --conf-path=./aria2.conf "${{ github.event.inputs.url }}"

      - name: Release Video
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.event.inputs.tag }}
          prerelease: false
          files: |
            ${{ github.event.inputs.path }}

      - name: Clean log
        uses: igorjs/gh-actions-clean-workflow@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          days_old: 1
