name: HLS to Release

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Video URL(HTTP/HTTPS OR Metalink)'
        required: true
      path:
        description: 'Video File Path(Wildcard support)'
        required: true
      tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup Aria2/FFmpeg
        run: |
          python aria2.py
          aria2c https://github.com/eugeneware/ffmpeg-static/releases/latest/download/linux-x64
          chmod +x linux-x64
          sudo mv linux-x64  /usr/local/bin/ffmpeg

      - name: Download video
        run: | 
            aria2c --conf-path=./aria2.conf "${{ github.event.inputs.url }}"

      - name: Update DHT
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          mv dht.dat dht
          mv dht6.dat dht6
          git pull
          mv dht dht.dat
          mv dht6 dht6.dat
          git add dht.dat dht6.dat
          git commit -m 'update'
          git push origin main

      - name: Process video
        run: |
          ffmpeg -hide_banner -i ${{ github.event.inputs.path }} -c copy -sn \
          -f hls -hls_time 60 -hls_list_size 0 -hls_segment_filename vue%d.ts index.ts
          rm -rf ${{ github.event.inputs.path }}

      - name: Release Video
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.event.inputs.tag }}
          prerelease: false
          files: |
            *.ts

      - name: Clean log
        uses: igorjs/gh-actions-clean-workflow@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          days_old: 1
