name: Video to Release

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Video URL(HTTP/HTTPS OR Metalink)'
        required: true
      path:
        description: 'Video File Path(Wildcard support)'
        required: true
      tag:
        description: 'Release Tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup FFmpeg
        run: |
          aria2c https://github.com/eugeneware/ffmpeg-static/releases/latest/download/linux-x64
          chmod +x linux-x64
          sudo mv linux-x64  /usr/local/bin/ffmpeg

      - name: Download video
        run: |
            python aria2.py
            wget -q https://github.com/P3TERX/aria2.conf/raw/master/dht.dat
            wget -q https://github.com/P3TERX/aria2.conf/raw/master/dht6.dat
            aria2c --conf-path=./aria2.conf "${{ github.event.inputs.url }}"

      - name: Process video
        run: |
          ffmpeg -hide_banner -i ${{ github.event.inputs.path }} \
                 -c copy -f hls -bsf:v h264_mp4toannexb \
                 -hls_time 60 -hls_list_size 0 -hls_segment_filename vue%d.ts index.ts
          rm -rf ${{ github.event.inputs.path }}

      - name: Release Video
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.event.inputs.tag }}
          prerelease: false
          files: |
            *.ts
