name: HLS to Repo

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Video URL(HTTP/HTTPS OR Metalink)'
        required: true
      path:
        description: 'Video File Path(Wildcard support)'
        required: true
      repo:
        description: 'Repo Name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup FFmpeg/Python/Aria2
        run: |
          aria2c https://github.com/eugeneware/ffmpeg-static/releases/latest/download/linux-x64
          chmod +x linux-x64
          sudo mv linux-x64  /usr/local/bin/ffmpeg
          pip --quiet install bs4
          python ./aria2/add_tracker.py

      - name: Get jav info
        run: |
            python javinfo.py ${{ github.event.inputs.repo }}

      - name: Download video
        run: |
            aria2c --conf-path=./aria2.conf "${{ github.event.inputs.url }}"

      - name: Update DHT
        run: |
          git config --local user.email "you@example.com"
          git config --local user.name "Your Name"
          git add ./aria2/dht.dat ./aria2/dht6.dat
          git commit -m 'update'
          git push -f origin main

      - name: Process video
        run: |
          #bash video_preview.sh ${{ github.event.inputs.path }} 480 4 4 preview.jpg
          ffmpeg -hide_banner -i ${{ github.event.inputs.path }} \
                 -c copy -f hls -bsf:v h264_mp4toannexb -hls_time 1 \
                 -hls_list_size 0 -hls_segment_filename %4d.ts index.m3u8
          rm -rf ${{ github.event.inputs.path }}

      - name: Setup Git
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      
      - name: Create Github repo
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          curl \
          -X POST \
          -H "Authorization: token $GH_TOKEN" \
          -H "Content-Type: application/json" \
          https://api.github.com/user/repos \
          -d "{\"name\": \"${{ github.event.inputs.repo }}\"}"
      
      - name: Push to Github
        env:
          REPO: ${{ github.event.inputs.repo }}
        run: |
          ## move video into dir
          mkdir -p dir/res/
          mv *.m3u8 *.ts dir/res/
          mkdir -p dir/img/
          ## move pictures into dir
          imgs=(*.jpg)
          if [ -f ${imgs[0]} ];then
            mv *.jpg dir/img/
          fi
          ## move index.html into dir
          mv index.html dir/
          ## get into dir and upload to github
          cd dir
          git init
          git add img res/*.m3u8 index.html
          git commit -m "Add img and index"
          git remote add origin git@github.com:$GITHUB_REPOSITORY_OWNER/$REPO.git
          git push -u origin master
          for i in {0..9};do
            for j in {0..9};do
              files=(res/$i$j??.ts)
              if [ -f ${files[0]} ];then
                git add "${files[@]}"
                git commit -m "$i$j st commit"
                git push
              else
                exit 0
              fi
            done
          done

      - name: Build site
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          cd home
          mkdir -p build
          mkdir -p page
          python build.py
          mv *.html css page build

      - name: Deploy site
        uses:  NickSchimek/deploy_jamstack_action@main
        with:
          build-dir: home/build

      - name: Clean log
        uses: igorjs/gh-actions-clean-workflow@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          days_old: 1
