name: HLS to Repo

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Video URL(HTTP/HTTPS OR Metalink)'
        required: true
      path:
        description: 'Video File Path(Wildcard support)'
        required: true
      repo:
        description: 'Repo Name'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024

      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup FFmpeg/Python/Aria2
        run: |
          aria2c https://github.com/eugeneware/ffmpeg-static/releases/latest/download/linux-x64
          chmod +x linux-x64 && sudo mv linux-x64  /usr/local/bin/ffmpeg
          pip --quiet install bs4 && python ./aria2/add_tracker.py

      - name: Get JAV info
        run: |
            python javinfo.py ${{ github.event.inputs.repo }}

      - name: Download video
        run: |
            aria2c --conf-path=./aria2/aria2.conf "${{ github.event.inputs.url }}"

      - name: Process video
        run: |
          #bash video_preview.sh ${{ github.event.inputs.path }} 480 4 4 preview.jpg
          ffmpeg -hide_banner -i ${{ github.event.inputs.path }} \
                 -c copy -sn -f hls -bsf:v h264_mp4toannexb -hls_time 1 \
                 -hls_list_size 0 -hls_segment_filename %4d.ts index.m3u8
          rm -rf ${{ github.event.inputs.path }}

      - name: Setup Git
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          echo "UserKnownHostsFile ~/.ssh/known_hosts" >> ~/.ssh/config
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
      
      - name: Create Github repo
        env:
          GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          curl \
          -X POST \
          -H "Authorization: token $GH_TOKEN" \
          -H "Content-Type: application/json" \
          https://api.github.com/user/repos \
          -d "{\"name\": \"${{ github.event.inputs.repo }}\"}"
      
      - name: Push to Github
        env:
          OWNER: ${{ GITHUB_REPOSITORY_OWNER }}
          REPO: ${{ github.event.inputs.repo }}
          TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          ## move video into dir
          mkdir -p dir/res/
          mv *.m3u8 *.ts dir/res/
          mkdir -p dir/img/
          ## move pictures into dir
          imgs=(*.jpg)
          if [ -f ${imgs[0]} ];then
            mv *.jpg dir/img/
          fi
          ## move index.html into dir
          mv index.html dir/
          ## get into dir and upload to github
          cd dir
          git init
          git add img res/*.m3u8 index.html
          git commit -m "Add img and index"
          git remote add origin https://${OWNER}:${TOKEN}@github.com/${OWNER}/${REPO}.git
          git push -u origin master
          for i in {0..9};do
            for j in {0..9};do
              files=(res/$i$j??.ts)
              if [ -f ${files[0]} ];then
                git add "${files[@]}"
                git commit -m "$i$j st commit"
                git push
              else
                exit 0
              fi
            done
          done

      # - name: Build & Deploy
      #   env:
      #     GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      #     TOKEN: ${{ github.token }}
      #     ACTOR: ${{ github.actor }}
      #     REPO: ${{ github.repository }}
      #   run: |
      #     cd home
      #     mkdir -p build
      #     mkdir -p page
      #     python build.py
      #     mv *.html css page build
      #     cd build
      #     git config --global init.defaultBranch main
      #     git init
      #     git config user.email "${ACTOR}@users.noreply.github.com"
      #     git config user.name "${ACTOR}"
      #     git add .
      #     git commit -m "Deploy ${GITHUB_SHA}"
      #     git push -f "https://${ACTOR}:${TOKEN}@github.com/${REPO}.git" main:gh-pages

      # - name: Delete workflow runs
      #   uses: Mattraks/delete-workflow-runs@v2
      #   with:
      #     token: ${{ github.token }}
      #     repository: ${{ github.repository }}
      #     retain_days: 1
      #     keep_minimum_runs: 1
