name: Transmission-cli

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL(HTTP/HTTPS OR Metalink)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Setup
        run: |
            sudo apt install transmission-cli -y
            #echo "net.core.rmem_max = 4194304" >> /etc/sysctl.conf
            #echo "net.core.wmem_max = 1048576" >> /etc/sysctl.conf
      
      - name: Download
        run: |
            transmission-cli -er -g ./transmission -w ./ "${{ github.event.inputs.url }}"
            ls -ll